apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: phoenix
  namespace: phoenix
  labels:
    app: phoenix
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: phoenix
  template:
    metadata:
      labels:
        app: phoenix
    spec:
      containers:
      - name: phoenix
        image: suhita/phoenix2.0:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: phoenix-c
  namespace: phoenix
  labels:
    app: phoenix
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30006
  selector:
    app: phoenix
